###############################################################################
###############################################################################

# Adjustable parameters

### List of screen names (lowercase) to process end-to-end. Example: [screen2022, screen2023]
SCREENS: [screen2022, screen2023]

### Source of counts data: "manuscript", "counts_only", "counts_metadata"
COUNTS_SOURCE: "counts_only"
### Filepath pattern for provided counts-with-metadata files 
### (used if COUNTS_SOURCE is "counts_metadata")
COUNTS_FILEPATH_PATTERN: "data/counts/{screen}_counts_with_metadata.tsv"

### Count filter thresholds
INITIAL_CONDITION_ID: "T0"
INDIVIDUAL_SGRNA_MEDIAN_THRESHOLD: 35
COMBINATION_SGRNA_COUNT_THRESHOLD: 50

### Counts column positions in counts files
#SCREEN2022_COUNTS_COLUMNS: [14, 15, 16, 17, 18, 19]
#SCREEN2023_COUNTS_COLUMNS: [14, 15, 16, 17, 18, 19]
COUNT_PREFIXES: ["T0", "DMSO", "TREATED"]
REPLICATES: ["R1", "R2"]

### Phenotype prefix map: mapping phenotype name -> [numerator_prefix, denominator_prefix]
### These are used by calculate_phenotypes to find columns like DMSO.R1, T0.R1 etc.
SCREEN2022_PHENOTYPE_PREFIX_MAP:
  Gamma: ["DMSO", "T0"]
  Tau: ["NIRAP", "T0"]
  Rho: ["NIRAP", "DMSO"]

PHENOTYPE_PREFIX_MAP:
  Gamma: ["DMSO", "T0"]
  Tau: ["TREATED", "T0"]
  Rho: ["TREATED", "DMSO"]

### Phenotype calculation parameters
PSEUDOCOUNT: 10
NORMALIZE: TRUE
AVERAGE_REPLICATES: TRUE

### Population doublings per (treatment,replicate), used if NORMALIZE is TRUE
SCREEN2022_DOUBLINGS:
  DMSO:
    R1: 7.19
    R2: 7.73
  NIRAP:
    R1: 5.32
    R2: 5.36

SCREEN2023_DOUBLINGS:
  DMSO:
    R1: 8.04
    R2: 7.98
  TREATED:
    R1: 5.40
    R2: 4.98

### Correlation filter parameters
NO_CORRELATION_THRESHOLD: 0.25

### Phenotypes to use for genetic interaction score calculation
GI_PHENOTYPES: ["Gamma", "Tau", "Rho"]

### Genetic interaction score calculation parameters
SCREEN2022_GI_SCORES: ["Gamma.OI.R1", "Gamma.OI.R2", "Gamma.OI.Avg", "Tau.OI.R1", "Tau.OI.R2", "Tau.OI.Avg"]
SCREEN2023_GI_SCORES: ["Gamma.OI.R1", "Gamma.OI.R2", "Gamma.OI.Avg", "Tau.OI.R1", "Tau.OI.R2", "Tau.OI.Avg"]

### Replicates used for differential score calculation
DIFFERENTIAL_SCORES: ["OI.R1", "OI.R2", "OI.Avg"]
HIT_THRESHOLD: 0.995
DIFFERENTIAL_HIT_THRESHOLD: 1

### Clustering parameters
PHENOTYPES_TO_CLUSTER: ["Gamma.OI.Avg", "Tau.OI.Avg", "Nu.OI.Avg"]

###############################################################################
###############################################################################

EXPECTED_COUNT_COLUMNS:
  - FirstPosition
  - FirstPseudogene
  - SecondPosition
  - SecondPseudogene
  - ConstructID
  - GuideCombinationID
  - PseudogeneCombinationID
  - PseudogeneCombinationName
  - Category
  - Control
  - Identical
  - Orientation